configName: pic32mz_ef_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2048EFH144
projectName: ''
settings:
  PackageFilter: aerospace;audio;aws_cloud;bootloader;bsp;bt;core;core_apps_pic32mz_ef;crypto;cryptoauthlib;cryptoauthlib_apps;csp;csp_apps_pic32mz_ef;expresslogic_threadx;gfx;gfx_apps;micrium_ucos3;motor_control;net;net_apps_pic32mz;quick_docs;touch;usb;wireless
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFH144.atdf
