format_version: v1.0
type: UniqueComponent
attributes: {id: drvExtPhyDp83848}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_INTMAC_PHY_ADDRESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: TCPIP_INTMAC_PHY_CONFIG_ALTERNATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: TCPIP_INTMAC_PHY_CONFIG_AUTO}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_INTMAC_PHY_CONFIG_RMII}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '404', y: '23', id: drvExtPhyDp83848}
