format_version: v1.0
type: UniqueComponent
attributes: {id: drvExtPhyLan8740}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_INTMAC_PHY_ADDRESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
- type: ElementPosition
  attributes: {x: '405', y: '19', id: drvExtPhyLan8740}
